### ISSUE TITLE
Can't plot Frame with HicCompare

### ISSUE THREAD

**Issue by azkalot1** [GangCaoLab/CoolBox#4]
Hi,

I am trying to make plot to compare two HiC tracks. 
As indicated in the tutorial I use 
```
type_A = Cool(path_A, style="window") + MinValue(1e-3)
type_B = Cool(path_B, style="window") + MinValue(1e-3)
hiccomp = HicCompare(type_A, type_B)
frame = XAxis() + hiccomp
frame.plot('chr9', 4000000, 6000000)
```
However, I get the error 
`TypeError: unsupported operand type(s) for +: 'int' and 'str'`
If I print properties of hiccomp, I see that it is set to "cool_auto"
So `frame.get_tracks_height()` returns `[2, 'cool_auto']`, so it cant combine them.
I fixed that by manually setting 
```
hiccomp.properties['width'] = 14
hiccomp.properties['height'] = 14
```

But after that, when I try to print a frame again I get
```
[ERROR:frame.py:113 -                 plot()] Error occured when plot track:
	track name: HicCompare.3
	track type:<class 'coolbox.core.track.HicCompare'>
	Error: <class 'AttributeError'> 'Cool' object has no attribute '_PlotHicCompare__fetch_matrix'
	occurred in "/home/skolchen/anaconda3/envs/cooltools/lib/python3.6/site-packages/coolbox-0.1.8-py3.6.egg/coolbox/plots/frame.py", line 102
[ERROR:frame.py:115 -                 plot()] 'Cool' object has no attribute '_PlotHicCompare__fetch_matrix'
Traceback (most recent call last):
  File "/home/skolchen/anaconda3/envs/cooltools/lib/python3.6/site-packages/coolbox-0.1.8-py3.6.egg/coolbox/plots/frame.py", line 102, in plot
    track.plot(ax, chrom, start, end)
  File "/home/skolchen/anaconda3/envs/cooltools/lib/python3.6/site-packages/coolbox-0.1.8-py3.6.egg/coolbox/plots/track/hiccompare.py", line 55, in plot
    arr1 = self.hic1.__fetch_matrix(genome_range)
AttributeError: 'Cool' object has no attribute '_PlotHicCompare__fetch_matrix'
```
How can I fix that?

**Comment by Nanguage** [comment]
The `HicCompare` is temporarily unavailable due to the current poor effect(some reason about adjust colorbar).
The `HiCDiff` can be used to substitute it in the new CoolBox version(>= 0.2.2), more detail you can reference this
[example](https://gangcaolab.github.io/CoolBox/_gallery/HiCDiff.html)
