### ISSUE TITLE
Some error when plot GTF

### ISSUE THREAD

**Issue by szbssg** [GangCaoLab/CoolBox#95]
when I want to plot GTF,a error come out.Does there are some problem about tabix ? I already installed it

![image](https://github.com/GangCaoLab/CoolBox/assets/122605041/484d7486-d16e-40ce-b583-6a8929b1b989)
[ERROR:frame.py:215 -                 plot()] Error occured when plot track:
	track name: GTF.9
	track type:<class 'coolbox.core.track.gtf.GTF'>
	Error: <class 'FileNotFoundError'> [Errno 2] No such file or directory: 'tabix'
	occurred in "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/frame/frame.py", line 209
[ERROR:frame.py:222 -                 plot()] [Errno 2] No such file or directory: 'tabix'
Traceback (most recent call last):
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/frame/frame.py", line 209, in plot
    track.plot(ax, copy(gr), gr2=copy(gr2))
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/track/gtf.py", line 127, in plot
    df = self.fetch_plot_data(gr)
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/track/base.py", line 134, in fetch_plot_data
    return self.fetch_data(gr, **kwargs)
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/track/gtf.py", line 85, in fetch_data
    return self.fetch_intervals(gr)
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/track/gtf.py", line 99, in fetch_intervals
    rows = [row for row in tabix_query(self.bgz_file, gr.chrom, gr.start, gr.end)]
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/core/track/gtf.py", line 99, in <listcomp>
    rows = [row for row in tabix_query(self.bgz_file, gr.chrom, gr.start, gr.end)]
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/site-packages/coolbox/utilities/bed.py", line 368, in tabix_query
    p = subp.Popen(['tabix', '-f', filename, query], stdout=subp.PIPE)
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/szb/.conda/envs/chipseq/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'tabix'

**Comment by Nanguage** [comment]
Could you try `!tabix` in the notebook, I guess maybe it's installed in a different environment with coolbox.

**Comment by szbssg** [comment]
![image](https://github.com/GangCaoLab/CoolBox/assets/122605041/a3502234-9236-4cad-ac86-2695e3a1fd55)
In notebook ,tabix can not be found . But in shell ,in chipseq envs tabix is well installed . I have no idea why tabix can not be found in notebook . I use ipykernel import chipseq envs into notebook .

**Comment by szbssg** [comment]
![image](https://github.com/GangCaoLab/CoolBox/assets/122605041/8b80166a-02a4-4f75-a1b5-37f29f8cb451)

**Comment by Nanguage** [comment]
You could check where the coolbox installed in your system using `which coolbox`
